[package]
name = "pngme"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version = "4.5.39", features = ["derive"]}
crc = "3.3.0"
fmt = "0.1.0"


[lib]
path = "src/lib.rs"

[workspace]
members = [
    ".",
    "PNGme-gui/src-tauri"
]


[[bin]]
name="pngme"
path="src/main.rs"


